#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=jwt_security;trustServerCertificate=false
#    username: sa
#    password: Tuandh111#$
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    database: sql_server
#    database-platform: org.hibernate.dialect.SQLServerDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

